version: "3"
services:
  www:
      build:
          context: .
          dockerfile: ./Dockerfile.www
      ports:
          - 4444:80
      volumes:
          - ../www:/var/www/html/
      networks:
          - default
  
