version: '3.1'

services:
  mongodb-primary:
    image: 'bitnami/mongodb:latest'
    environment:
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_PASSWORD=ROOT_PASSWORD
      - MONGODB_REPLICA_SET_KEY=REPLICA_KEY
    volumes:
      - mongodb-master-data:/bitnami
    ports:
      - "27017:27017"

  mongodb-secondary:
    image: 'bitnami/mongodb:latest'
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_PRIMARY_HOST=mongodb-primary
      - MONGODB_PRIMARY_ROOT_PASSWORD=ROOT_PASSWORD
      - MONGODB_REPLICA_SET_KEY=REPLICA_KEY
      - MONGODB_PRIMARY_PORT_NUMBER=27017

  mongodb-arbiter:
    image: 'bitnami/mongodb:latest'
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_REPLICA_SET_MODE=arbiter
      - MONGODB_PRIMARY_HOST=mongodb-primary
      - MONGODB_PRIMARY_ROOT_PASSWORD=ROOT_PASSWORD
      - MONGODB_REPLICA_SET_KEY=REPLICA_KEY
      - MONGODB_PRIMARY_PORT_NUMBER=27017

volumes:
  mongodb-master-data:
    external:
      name: mongodb-master-data

